/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import java.util.Locale;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class FormPrincipalLoja extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipalLoja
     */
    public FormPrincipalLoja() {
        initComponents();
    }

    FormPrincipalLoja(FormLogin aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnAnterior2 = new javax.swing.JButton();
        btnAnterior3 = new javax.swing.JButton();
        btnAnterior4 = new javax.swing.JButton();
        painelNavegacao = new javax.swing.JPanel();
        btnProduto = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnFuncionario = new javax.swing.JButton();
        btnCidade = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAnterior5 = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuProduto = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenuItem();
        menuCidade = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        menuRealizaVenda = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela inicial");
        setBackground(new java.awt.Color(167, 191, 78));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setToolTipText("");
        jPanel2.setAlignmentX(2.0F);
        jPanel2.setAlignmentY(2.0F);
        jPanel2.setAutoscrolls(true);
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setFont(jPanel2.getFont());
        jPanel2.setPreferredSize(new java.awt.Dimension(640, 360));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(null);
        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 0, 0, 0);

        btnAnterior2.setBackground(new java.awt.Color(167, 191, 78));
        btnAnterior2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnterior2.setForeground(new java.awt.Color(51, 51, 51));
        btnAnterior2.setText("FAZER LOGIN");
        btnAnterior2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnterior2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnterior2);
        btnAnterior2.setBounds(690, 110, 210, 40);

        btnAnterior3.setBackground(new java.awt.Color(167, 191, 78));
        btnAnterior3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAnterior3.setForeground(new java.awt.Color(51, 51, 51));
        btnAnterior3.setText("INFORMAÇÕES DO SOFTWARE");
        btnAnterior3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnterior3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnterior3);
        btnAnterior3.setBounds(690, 210, 210, 40);

        btnAnterior4.setBackground(new java.awt.Color(167, 191, 78));
        btnAnterior4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAnterior4.setForeground(new java.awt.Color(51, 51, 51));
        btnAnterior4.setText("SAIR");
        btnAnterior4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnterior4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnterior4);
        btnAnterior4.setBounds(690, 260, 210, 40);

        painelNavegacao.setBackground(new java.awt.Color(167, 191, 78));
        painelNavegacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visualizar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 3, 14))); // NOI18N
        painelNavegacao.setLayout(new java.awt.GridLayout(1, 0));

        btnProduto.setBackground(new java.awt.Color(51, 51, 51));
        btnProduto.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnProduto.setForeground(new java.awt.Color(204, 204, 204));
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cart_add.png"))); // NOI18N
        btnProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto.setIconTextGap(9);
        btnProduto.setMargin(new java.awt.Insets(4, 16, 4, 16));
        btnProduto.setMaximumSize(new java.awt.Dimension(69, 45));
        btnProduto.setMinimumSize(new java.awt.Dimension(69, 45));
        btnProduto.setName(""); // NOI18N
        btnProduto.setPreferredSize(new java.awt.Dimension(73, 59));
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        painelNavegacao.add(btnProduto);

        btnCliente.setBackground(new java.awt.Color(51, 51, 51));
        btnCliente.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_add.png"))); // NOI18N
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        painelNavegacao.add(btnCliente);

        btnFuncionario.setBackground(new java.awt.Color(51, 51, 51));
        btnFuncionario.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnFuncionario.setForeground(new java.awt.Color(204, 204, 204));
        btnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_gray.png"))); // NOI18N
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });
        painelNavegacao.add(btnFuncionario);

        btnCidade.setBackground(new java.awt.Color(51, 51, 51));
        btnCidade.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnCidade.setForeground(new java.awt.Color(204, 204, 204));
        btnCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/house.png"))); // NOI18N
        btnCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCidadeActionPerformed(evt);
            }
        });
        painelNavegacao.add(btnCidade);

        jPanel2.add(painelNavegacao);
        painelNavegacao.setBounds(670, 380, 230, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo400.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(140, 20, 420, 430);

        jPanel1.setBackground(new java.awt.Color(167, 191, 78));
        jPanel1.add(jPanel3);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(-20, -30, 120, 670);

        btnAnterior5.setBackground(new java.awt.Color(167, 191, 78));
        btnAnterior5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAnterior5.setForeground(new java.awt.Color(51, 51, 51));
        btnAnterior5.setText("REALIZAR VENDA");
        btnAnterior5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnterior5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnterior5);
        btnAnterior5.setBounds(690, 160, 210, 40);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 980, 550));

        barraMenu.setBackground(new java.awt.Color(167, 191, 78));

        menuCadastro.setBackground(new java.awt.Color(167, 191, 78));
        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        menuCadastro.setText("Cadastro");

        menuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cart_add.png"))); // NOI18N
        menuProduto.setText("Produto");
        menuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuProduto);

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_add.png"))); // NOI18N
        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCliente);

        menuFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_gray.png"))); // NOI18N
        menuFuncionario.setText("Funcionario");
        menuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(menuFuncionario);

        menuCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/house.png"))); // NOI18N
        menuCidade.setText("Cidade");
        menuCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCidadeActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCidade);

        barraMenu.add(menuCadastro);

        menuVenda.setBackground(new java.awt.Color(167, 191, 78));
        menuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chart_bar.png"))); // NOI18N
        menuVenda.setText("Venda");
        menuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendaActionPerformed(evt);
            }
        });

        menuRealizaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coins.png"))); // NOI18N
        menuRealizaVenda.setText("Realizar Venda");
        menuRealizaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRealizaVendaActionPerformed(evt);
            }
        });
        menuVenda.add(menuRealizaVenda);

        barraMenu.add(menuVenda);

        menuAjuda.setBackground(new java.awt.Color(167, 191, 78));
        menuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bullet_error.png"))); // NOI18N
        menuAjuda.setText("Ajuda");
        menuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudaActionPerformed(evt);
            }
        });

        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuSobre);

        barraMenu.add(menuAjuda);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutoActionPerformed
        FormProduto form = new FormProduto(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_menuProdutoActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        FormCliente form = new FormCliente(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        JOptionPane.showMessageDialog(null,"Sistema EMPORIUM - STORE\nDireitos reservado\nDev Athos Telini\nVersão 1.0");
    }//GEN-LAST:event_menuSobreActionPerformed

    private void menuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAjudaActionPerformed

    private void menuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendaActionPerformed
        
    }//GEN-LAST:event_menuVendaActionPerformed

    private void menuRealizaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRealizaVendaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        FormVenda form = new FormVenda(this, true);
       // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); //não deixa fechar pelo X
       form.setLocationRelativeTo(null);
      // form.setResizable(false);
       form.setVisible(true);
    }//GEN-LAST:event_menuRealizaVendaActionPerformed

    private void menuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioActionPerformed
         // TODO add your handling code here:
         FormFuncionario form  = new FormFuncionario(this,true);
        //this: chama a partir deste form
        // true: Modal: sobre o form principal e não deixa acessa-lo
       // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        // não deixa fechar o form pelo x
        form.setLocationRelativeTo(null); // centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); //mostra o form
    }//GEN-LAST:event_menuFuncionarioActionPerformed

    private void menuCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCidadeActionPerformed
        FormCidade form = new FormCidade(this,true);
        //form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        
    }//GEN-LAST:event_menuCidadeActionPerformed

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
        // TODO add your handling code here:
         FormFuncionario form  = new FormFuncionario(this,true);
        //this: chama a partir deste form
        // true: Modal: sobre o form principal e não deixa acessa-lo
       // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        // não deixa fechar o form pelo x
        form.setLocationRelativeTo(null); // centro
        form.setResizable(false); // retira o botão maximizar
        form.setVisible(true); //mostra o form
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        FormCliente form = new FormCliente(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        FormProduto form = new FormProduto(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnAnterior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior2ActionPerformed
       
       FormLogin formLogin= new FormLogin();
       formLogin.setVisible(true);
       formLogin.setLocationRelativeTo(null);
               
               
    }//GEN-LAST:event_btnAnterior2ActionPerformed

    private void btnAnterior3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null," O software de cadastro e venda de produtos de uma \n loja ficticia chamada EMPORIUM STORE ,\n desenvolvido por mim  aluno Athos Telini\n como parte do trabalho da disciplina de Linguagem de Programação 2\n utilizando a plataforma NetBeans 8.2 e a linguagem de programação Java \n com  a ferramenta de banco de dados Heidi SQL");

    }//GEN-LAST:event_btnAnterior3ActionPerformed

    private void btnAnterior4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnAnterior4ActionPerformed

    private void btnCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCidadeActionPerformed
        // TODO add your handling code here:
        FormCidade form = new FormCidade(this,true);
        //form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_btnCidadeActionPerformed

    private void btnAnterior5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior5ActionPerformed
            // TODO add your handling code here:
        // TODO add your handling code here:
        FormVenda form = new FormVenda(this, true);
       // form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); //não deixa fechar pelo X
       form.setLocationRelativeTo(null);
      // form.setResizable(false);
       form.setVisible(true);
    }//GEN-LAST:event_btnAnterior5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FormPrincipalLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FormPrincipalLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FormPrincipalLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FormPrincipalLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                FormPrincipalLoja form = new FormPrincipalLoja();
                form.setLocationRelativeTo(null);//janela no centro
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnAnterior2;
    private javax.swing.JButton btnAnterior3;
    private javax.swing.JButton btnAnterior4;
    private javax.swing.JButton btnAnterior5;
    private javax.swing.JButton btnCidade;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JButton btnProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCidade;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuFuncionario;
    private javax.swing.JMenuItem menuProduto;
    private javax.swing.JMenuItem menuRealizaVenda;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenu menuVenda;
    private javax.swing.JPanel painelNavegacao;
    // End of variables declaration//GEN-END:variables
}
